version: "3.4"

services:
  clientapp:
    image: daylight-clientapp-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    container_name: daylight-clientapp
